### PR TITLE
Update Readme poin 9. - anggito

### PR DESCRIPTION
**Pull request by Anggito02**
menambahkan data github dan linkedin anggito pada poin nomor 9

### CODE REVIEW

**Review by yoursemicolon — APPROVED** [review]
resolve conflict ya

**Comment by Anggito02** [comment]
> resolve conflict ya
Okee mbakk, sudah

**Comment by yoursemicolon** [comment]
> > resolve conflict ya
> > Okee mbakk, sudah

sipp👍🏻

**Comment by yoursemicolon** [comment]
okesip👍🏻

**Pull request merged**
